/**
 * Mock meal plan data generated by sredaAgent
 */

export const mealPlans = {
  default: [
    {
      day: 1,
      meals: [
        { type: 'breakfast', name: 'Омлет с овощами и шпинатом', time: '15 мин', kcal: 280, protein: 22, fat: 18, carbs: 8, tags: ['белок', 'быстро'] },
        { type: 'lunch', name: 'Боул с индейкой и гречкой', time: '25 мин', kcal: 420, protein: 35, fat: 12, carbs: 42, tags: ['белок', 'клетчатка', 'сбалансированно'] },
        { type: 'dinner', name: 'Лосось с брокколи на пару', time: '20 мин', kcal: 350, protein: 28, fat: 18, carbs: 12, tags: ['омега-3', 'белок', 'без сахара'] },
        { type: 'snack', name: 'Греческий йогурт с голубикой', time: '3 мин', kcal: 130, protein: 12, fat: 3, carbs: 14, tags: ['белок', 'антиоксиданты'] },
      ]
    },
    {
      day: 2,
      meals: [
        { type: 'breakfast', name: 'Творожный завтрак без сахара', time: '5 мин', kcal: 220, protein: 20, fat: 8, carbs: 12, tags: ['белок', 'быстро', 'без сахара'] },
        { type: 'lunch', name: 'Суп-крем из чечевицы + хлеб', time: '5 мин', kcal: 320, protein: 15, fat: 8, carbs: 40, tags: ['клетчатка', 'быстро'] },
        { type: 'dinner', name: 'Куриная грудка с киноа и овощами', time: '30 мин', kcal: 380, protein: 32, fat: 10, carbs: 35, tags: ['белок', 'сложные углеводы'] },
        { type: 'snack', name: 'Хумус с огурцом', time: '2 мин', kcal: 150, protein: 6, fat: 9, carbs: 12, tags: ['клетчатка', 'быстро'] },
      ]
    },
    {
      day: 3,
      meals: [
        { type: 'breakfast', name: 'Яйца-пашот с авокадо на тосте', time: '10 мин', kcal: 340, protein: 16, fat: 22, carbs: 20, tags: ['полезные жиры', 'белок'] },
        { type: 'lunch', name: 'Салат с тунцом и овощами', time: '3 мин', kcal: 180, protein: 18, fat: 9, carbs: 8, tags: ['белок', 'быстро', 'низкокалорийно'] },
        { type: 'dinner', name: 'Гречка с индейкой и шпинатом', time: '20 мин', kcal: 390, protein: 30, fat: 8, carbs: 45, tags: ['белок', 'железо', 'сложные углеводы'] },
        { type: 'snack', name: 'Орехи + протеиновый батончик', time: '0 мин', kcal: 280, protein: 14, fat: 18, carbs: 16, tags: ['белок', 'удобно'] },
      ]
    },
    {
      day: 4,
      meals: [
        { type: 'breakfast', name: 'Греческий йогурт с орехами', time: '3 мин', kcal: 250, protein: 15, fat: 16, carbs: 12, tags: ['белок', 'быстро'] },
        { type: 'lunch', name: 'Боул с курицей и киноа (готовый)', time: '3 мин', kcal: 320, protein: 28, fat: 12, carbs: 25, tags: ['белок', 'быстро'] },
        { type: 'dinner', name: 'Омлет с помидорами и сыром', time: '10 мин', kcal: 300, protein: 20, fat: 20, carbs: 6, tags: ['белок', 'быстро'] },
        { type: 'snack', name: 'Кефир', time: '0 мин', kcal: 75, protein: 4.5, fat: 3.75, carbs: 6, tags: ['пробиотики', 'быстро'] },
      ]
    },
    {
      day: 5,
      meals: [
        { type: 'breakfast', name: 'Творог с голубикой и орехами', time: '5 мин', kcal: 290, protein: 22, fat: 14, carbs: 18, tags: ['белок', 'антиоксиданты'] },
        { type: 'lunch', name: 'Суп из чечевицы + салат', time: '5 мин', kcal: 280, protein: 14, fat: 6, carbs: 35, tags: ['клетчатка', 'быстро'] },
        { type: 'dinner', name: 'Лосось с овощами на гриле', time: '25 мин', kcal: 380, protein: 26, fat: 20, carbs: 15, tags: ['омега-3', 'белок'] },
        { type: 'snack', name: 'Хумус с морковью', time: '2 мин', kcal: 140, protein: 5, fat: 8, carbs: 12, tags: ['клетчатка', 'быстро'] },
      ]
    },
  ],
};

export const mealTypeLabels = {
  breakfast: 'Завтрак',
  lunch: 'Обед',
  dinner: 'Ужин',
  snack: 'Перекус',
};
