/**
 * Mock VkusVill product catalog
 * Structure mirrors what VkusVill MCP would return via vkusvill_product_details
 */

export const products = [
  // Белок
  {
    id: 'p001',
    xml_id: 'vv_turkey_fillet',
    name: 'Филе индейки охлаждённое',
    category: 'protein',
    price: 489,
    weight: '500 г',
    kcal: 114,
    protein: 23.6,
    fat: 1.7,
    carbs: 0,
    sugar: 0,
    rating: 4.8,
    tags: ['белок', 'без сахара', 'без глютена'],
    reason: 'Высокое содержание белка при минимуме жира — идеально для контроля веса и энергии.',
    composition: 'Филе индейки охлаждённое. Без добавок.',
    image: '#4ECDC4',
  },
  {
    id: 'p002',
    xml_id: 'vv_chicken_breast',
    name: 'Куриная грудка без кожи',
    category: 'protein',
    price: 359,
    weight: '500 г',
    kcal: 110,
    protein: 23,
    fat: 1.2,
    carbs: 0,
    sugar: 0,
    rating: 4.7,
    tags: ['белок', 'без сахара', 'бюджетно'],
    reason: 'Классический источник белка по доступной цене.',
    composition: 'Куриная грудка охлаждённая, без кожи.',
    image: '#FF6B6B',
  },
  {
    id: 'p003',
    xml_id: 'vv_salmon_fillet',
    name: 'Филе лосося',
    category: 'protein',
    price: 699,
    weight: '300 г',
    kcal: 208,
    protein: 20,
    fat: 13.6,
    carbs: 0,
    sugar: 0,
    rating: 4.9,
    tags: ['белок', 'омега-3', 'без сахара'],
    reason: 'Богат омега-3 жирными кислотами, поддерживает здоровье сердца и мозга.',
    composition: 'Филе лосося атлантического охлаждённое.',
    image: '#FF8A5C',
  },
  {
    id: 'p004',
    xml_id: 'vv_eggs_10',
    name: 'Яйца куриные С1, 10 шт',
    category: 'protein',
    price: 149,
    weight: '10 шт',
    kcal: 157,
    protein: 12.7,
    fat: 11.5,
    carbs: 0.7,
    sugar: 0,
    rating: 4.6,
    tags: ['белок', 'бюджетно', 'быстро'],
    reason: 'Универсальный источник белка для быстрых завтраков.',
    composition: 'Яйца куриные пищевые столовые, категория С1.',
    image: '#FFE66D',
  },
  {
    id: 'p005',
    xml_id: 'vv_cottage_cheese',
    name: 'Творог 5% без добавок',
    category: 'protein',
    price: 129,
    weight: '300 г',
    kcal: 121,
    protein: 17,
    fat: 5,
    carbs: 1.8,
    sugar: 1.8,
    rating: 4.7,
    tags: ['белок', 'кальций', 'бюджетно'],
    reason: 'Много белка и кальция, минимум углеводов.',
    composition: 'Молоко нормализованное, закваска молочнокислых культур.',
    image: '#F8F4E8',
  },
  {
    id: 'p006',
    xml_id: 'vv_greek_yogurt',
    name: 'Йогурт греческий без сахара',
    category: 'dairy',
    price: 89,
    weight: '200 г',
    kcal: 66,
    protein: 10,
    fat: 2,
    carbs: 3.5,
    sugar: 3.5,
    rating: 4.8,
    tags: ['белок', 'без сахара', 'пробиотики'],
    reason: 'Высокобелковый йогурт без добавленного сахара — отличный перекус или основа для завтрака.',
    composition: 'Молоко обезжиренное, сливки, закваска.',
    image: '#E8F5E9',
  },
  // Крупы / сложные углеводы
  {
    id: 'p007',
    xml_id: 'vv_buckwheat',
    name: 'Гречка зелёная',
    category: 'grains',
    price: 179,
    weight: '500 г',
    kcal: 310,
    protein: 12.6,
    fat: 3.3,
    carbs: 62,
    sugar: 0,
    rating: 4.5,
    tags: ['клетчатка', 'сложные углеводы', 'без глютена'],
    reason: 'Сложные углеводы с низким гликемическим индексом — стабильная энергия.',
    composition: 'Крупа гречневая зелёная.',
    image: '#8D6E63',
  },
  {
    id: 'p008',
    xml_id: 'vv_quinoa',
    name: 'Киноа белая',
    category: 'grains',
    price: 299,
    weight: '300 г',
    kcal: 368,
    protein: 14,
    fat: 6,
    carbs: 57,
    sugar: 0,
    rating: 4.6,
    tags: ['белок', 'клетчатка', 'без глютена'],
    reason: 'Полноценный растительный белок + клетчатка.',
    composition: 'Киноа белая.',
    image: '#FFF9C4',
  },
  {
    id: 'p009',
    xml_id: 'vv_wholegrain_bread',
    name: 'Хлеб цельнозерновой',
    category: 'grains',
    price: 99,
    weight: '300 г',
    kcal: 220,
    protein: 8,
    fat: 2,
    carbs: 40,
    sugar: 2,
    rating: 4.4,
    tags: ['клетчатка', 'сложные углеводы'],
    reason: 'Цельнозерновая мука — больше клетчатки, медленные углеводы.',
    composition: 'Мука пшеничная цельнозерновая, вода, дрожжи, соль.',
    image: '#D7CCC8',
  },
  // Овощи и зелень
  {
    id: 'p010',
    xml_id: 'vv_broccoli',
    name: 'Брокколи свежая',
    category: 'vegetables',
    price: 189,
    weight: '400 г',
    kcal: 34,
    protein: 2.8,
    fat: 0.4,
    carbs: 7,
    sugar: 1.7,
    rating: 4.5,
    tags: ['клетчатка', 'витамины', 'низкокалорийно'],
    reason: 'Много клетчатки и витаминов при минимуме калорий.',
    composition: 'Брокколи свежая.',
    image: '#66BB6A',
  },
  {
    id: 'p011',
    xml_id: 'vv_avocado',
    name: 'Авокадо',
    category: 'vegetables',
    price: 149,
    weight: '1 шт',
    kcal: 160,
    protein: 2,
    fat: 15,
    carbs: 9,
    sugar: 0.7,
    rating: 4.3,
    tags: ['полезные жиры', 'клетчатка'],
    reason: 'Полезные жиры для сытости и здоровья сердца.',
    composition: 'Авокадо.',
    image: '#A5D6A7',
  },
  {
    id: 'p012',
    xml_id: 'vv_spinach',
    name: 'Шпинат свежий',
    category: 'vegetables',
    price: 139,
    weight: '200 г',
    kcal: 23,
    protein: 2.9,
    fat: 0.4,
    carbs: 3.6,
    sugar: 0.4,
    rating: 4.4,
    tags: ['железо', 'витамины', 'низкокалорийно'],
    reason: 'Богат железом и фолиевой кислотой.',
    composition: 'Шпинат свежий.',
    image: '#2E7D32',
  },
  {
    id: 'p013',
    xml_id: 'vv_tomatoes',
    name: 'Помидоры черри',
    category: 'vegetables',
    price: 199,
    weight: '300 г',
    kcal: 18,
    protein: 0.9,
    fat: 0.2,
    carbs: 3.9,
    sugar: 2.6,
    rating: 4.6,
    tags: ['витамины', 'антиоксиданты', 'низкокалорийно'],
    reason: 'Ликопин + витамин C, отлично для салатов.',
    composition: 'Помидоры черри свежие.',
    image: '#EF5350',
  },
  {
    id: 'p014',
    xml_id: 'vv_cucumber',
    name: 'Огурцы свежие',
    category: 'vegetables',
    price: 109,
    weight: '400 г',
    kcal: 15,
    protein: 0.7,
    fat: 0.1,
    carbs: 3.6,
    sugar: 1.7,
    rating: 4.5,
    tags: ['низкокалорийно', 'гидратация'],
    reason: 'Минимум калорий, освежает и увлажняет.',
    composition: 'Огурцы свежие.',
    image: '#81C784',
  },
  // Перекусы
  {
    id: 'p015',
    xml_id: 'vv_hummus',
    name: 'Хумус классический',
    category: 'snacks',
    price: 179,
    weight: '200 г',
    kcal: 166,
    protein: 8,
    fat: 10,
    carbs: 14,
    sugar: 0,
    rating: 4.7,
    tags: ['белок', 'клетчатка', 'без сахара'],
    reason: 'Растительный белок + полезные жиры, сытный перекус.',
    composition: 'Нут, тахини, оливковое масло, лимонный сок, чеснок, соль.',
    image: '#FFE0B2',
  },
  {
    id: 'p016',
    xml_id: 'vv_nuts_mix',
    name: 'Смесь орехов без соли',
    category: 'snacks',
    price: 349,
    weight: '200 г',
    kcal: 607,
    protein: 20,
    fat: 54,
    carbs: 12,
    sugar: 4,
    rating: 4.8,
    tags: ['белок', 'полезные жиры', 'магний'],
    reason: 'Магний для восстановления, полезные жиры для сытости.',
    composition: 'Миндаль, кешью, грецкий орех, фундук.',
    image: '#A1887F',
  },
  {
    id: 'p017',
    xml_id: 'vv_protein_bar',
    name: 'Батончик протеиновый без сахара',
    category: 'snacks',
    price: 129,
    weight: '50 г',
    kcal: 180,
    protein: 20,
    fat: 7,
    carbs: 8,
    sugar: 0,
    rating: 4.4,
    tags: ['белок', 'без сахара', 'удобно'],
    reason: 'Быстрый перекус с высоким содержанием белка.',
    composition: 'Изолят сывороточного белка, какао-масло, эритрит, клетчатка.',
    image: '#795548',
  },
  // Готовые решения
  {
    id: 'p018',
    xml_id: 'vv_soup_lentil',
    name: 'Суп-крем из чечевицы',
    category: 'ready',
    price: 249,
    weight: '400 г',
    kcal: 98,
    protein: 7,
    fat: 3,
    carbs: 12,
    sugar: 1,
    rating: 4.6,
    tags: ['белок', 'клетчатка', 'быстро'],
    reason: 'Готовый обед за 3 минуты — белок + клетчатка из чечевицы.',
    composition: 'Чечевица, морковь, лук, оливковое масло, специи.',
    image: '#FF7043',
  },
  {
    id: 'p019',
    xml_id: 'vv_bowl_chicken',
    name: 'Боул с курицей и киноа',
    category: 'ready',
    price: 399,
    weight: '350 г',
    kcal: 320,
    protein: 28,
    fat: 12,
    carbs: 25,
    sugar: 2,
    rating: 4.7,
    tags: ['белок', 'сбалансированно', 'быстро'],
    reason: 'Сбалансированный обед: белок + сложные углеводы + овощи.',
    composition: 'Куриная грудка, киноа, брокколи, авокадо, соус.',
    image: '#26A69A',
  },
  {
    id: 'p020',
    xml_id: 'vv_salad_green',
    name: 'Салат с тунцом и овощами',
    category: 'ready',
    price: 329,
    weight: '250 г',
    kcal: 180,
    protein: 18,
    fat: 9,
    carbs: 8,
    sugar: 2,
    rating: 4.5,
    tags: ['белок', 'низкокалорийно', 'быстро'],
    reason: 'Лёгкий обед с высоким содержанием белка.',
    composition: 'Тунец, микс салатов, помидоры черри, огурец, оливковое масло.',
    image: '#43A047',
  },
  // Молочные / альтернативы
  {
    id: 'p021',
    xml_id: 'vv_oat_milk',
    name: 'Молоко овсяное',
    category: 'dairy',
    price: 169,
    weight: '1 л',
    kcal: 45,
    protein: 1,
    fat: 1.5,
    carbs: 7,
    sugar: 4,
    rating: 4.5,
    tags: ['без лактозы', 'растительное'],
    reason: 'Альтернатива молоку без лактозы.',
    composition: 'Вода, овёс, масло подсолнечное, соль.',
    image: '#FFF8E1',
  },
  {
    id: 'p022',
    xml_id: 'vv_kefir',
    name: 'Кефир 2.5%',
    category: 'dairy',
    price: 79,
    weight: '500 мл',
    kcal: 50,
    protein: 3,
    fat: 2.5,
    carbs: 4,
    sugar: 4,
    rating: 4.6,
    tags: ['пробиотики', 'кальций', 'бюджетно'],
    reason: 'Пробиотики для здоровья кишечника.',
    composition: 'Молоко нормализованное, закваска кефирных грибков.',
    image: '#F3E5F5',
  },
  // Ягоды
  {
    id: 'p023',
    xml_id: 'vv_blueberries',
    name: 'Голубика свежая',
    category: 'vegetables',
    price: 299,
    weight: '200 г',
    kcal: 57,
    protein: 0.7,
    fat: 0.3,
    carbs: 14,
    sugar: 10,
    rating: 4.7,
    tags: ['антиоксиданты', 'витамины'],
    reason: 'Антиоксиданты для мозга и иммунитета.',
    composition: 'Голубика свежая.',
    image: '#5C6BC0',
  },
];

// Budget alternatives (cheaper versions)
export const budgetAlternatives = {
  'p001': { ...products[1], reason: 'Дешевле индейки, но так же богата белком.' },
  'p003': { ...products[1], reason: 'Куриная грудка — бюджетная альтернатива лососю с высоким белком.' },
  'p008': { ...products[6], reason: 'Гречка дешевле киноа, но тоже даёт сложные углеводы.' },
  'p016': { ...products[14], reason: 'Хумус — более бюджетный источник растительного белка.' },
};

// High protein alternatives
export const proteinAlternatives = {
  'p009': { ...products[4], reason: 'Творог содержит 17 г белка на порцию — больше, чем хлеб.' },
  'p010': { ...products[0], reason: 'Индейка — один из лучших источников белка.' },
  'p021': { ...products[5], reason: 'Греческий йогурт содержит 10 г белка vs 1 г в овсяном молоке.' },
};

export const categoryLabels = {
  protein: 'Белок',
  vegetables: 'Овощи и зелень',
  grains: 'Крупы / сложные углеводы',
  dairy: 'Молочные / альтернативы',
  snacks: 'Перекусы',
  ready: 'Готовые решения',
};

export function getProductsByCategory(productIds) {
  const items = productIds ? products.filter(p => productIds.includes(p.id)) : products;
  const grouped = {};
  items.forEach(p => {
    if (!grouped[p.category]) grouped[p.category] = [];
    grouped[p.category].push(p);
  });
  return grouped;
}
